export default [
    {
      id: 1,
      subject: "Web-based Mobile App Development",
      location: "Hendon",
      price: 100,
      spaces: 5,
      image: "./images/1.svg",
    },
    {
      id: 2,
      subject: "Business Intelligence",
      location: "Kent",
      price: 250,
      spaces: 5,
      image: "./images/2.svg",
    },
    {
      id: 3,
      subject: "Advanced Web Development with Big Data",
      location: "Finchley",
      price: 300,
      spaces: 5,
      image: "./images/3.svg",
    },
    {
      id: 4,
      subject: "Artificial Intelligence",
      location: "Golders Green",
      price: 1000,
      spaces: 5,
      image: "./images/4.svg",
    },
    {
      id: 5,
      subject: "Strategic Information Systems",
      location: "Cricklewood",
      price: 250,
      spaces: 5,
      image: "./images/5.svg",
    },
    {
      id: 6,
      subject: "UX Design",
      location: "Colindale",
      price: 150,
      spaces: 5,
      image: "./images/6.svg",
    },
    {
      id: 7,
      subject: "Novel Interaction Technology",
      location: "Neasden",
      price: 200,
      spaces: 5,
      image: "./images/7.svg",
    },
    {
      id: 8,
      subject: "Digital Media Technology",
      location: "Edgware",
      price: 200,
      spaces: 5,
      image: "./images/8.svg",
    },
    {
      id: 9,
      subject: "Cybersecurity",
      location: "Kingsbury",
      price: 850,
      spaces: 5,
      image: "./images/9.svg",
    },
    {
      id: 10,
      subject: "Deep Learning and Computer Vision",
      location: "Luton",
      price: 800,
      spaces: 5,
      image: "./images/10.svg",
    },
  ]
  